name: Publish Python 🐍 distributions 📦 to PyPI

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build-n-publish:
    permissions:
      id-token: write
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pip install -r test-requirements.txt
        python -m unittest discover -s tests
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
    - name: Install pypa/build
      run: python -m pip install build
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.8
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}  # Use OIDC token as the default password
